[tool.ruff]
line-length = 120
select = ["ALL"]
ignore = [
    "ANN401", #Disallow Any
    "D401", #Imperative mood
    "RUF012" #ignore till https://github.com/astral-sh/ruff/issues/5243
]
target-version = "py311"
fix = true
show-fixes = true
[tool.ruff.pydocstyle]
convention = "numpy"

[tool.docformatter]
recursive = true
wrap-summaries = 120
wrap-descriptions = 120

[tool.black]
line-length = 120

[pycodestyle]
max-line-length = 120
exclude = ["venv"]


[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true

[tool.isort]
line_length = 120
skip = ["venv"]
profile = "black"
