name: Pytest
on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  tests:
    name: >-
      Pytest - Python ${{ matrix.PYTHON_VERSION }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { PYTHON_VERSION: '3.11' }
    steps:
      - name: "Checkout to repository"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: "Run tests"
        uses: pavelzw/pytest-action@v2
        with:
          report-title: >-
            Pytest - Python ${{ matrix.PYTHON_VERSION }}
